version: "3.8"
services:

    # PHP service
    php:
        build:
            context: .
            target: php
        container_name: php
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8080:8000
        depends_on:
            - database
            - redis

    # node
    node:
        build:
            context: .
            target: node
        container_name: node
        volumes:
            - .:/usr/src
            - ./node_modules:/usr/src/node_modules
        tty: true

    # Database server
    database:
        image: mysql:8.0
        container_name: mysql
        ports:
            - 3307:3306
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql

    # Redis server
    redis:
        image: redis:alpine
        container_name: redis
        command: redis-server --appendonly yes
        ports:
            - 6379:6379

    # phpmyadmin
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        depends_on:
            - database
        environment:
            - PMA_HOST=${DB_HOST}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        ports:
            - 9001:80

volumes:
    db-data: ~
